### ISSUE TITLE
Support for \[ \] and \( \) math modes

### ISSUE THREAD

**Issue by ahonkela** [polymode/poly-markdown#4]
It would be great if you could add support for display math using \[ \] and inline math using \( \).
These should be easier to catch than $ and $$ and I believe they are currently the recommended form for LaTeX (see e.g. http://texblog.net/latex-archive/maths/inline-math-mode/).

**Comment by vspinu** [comment]
Which markdown process supports that syntax? I have used pandoc specification and it does not include the above.

**Comment by ahonkela** [comment]
It seems to be a pandoc extension tex_math_single_backslash that is enabled in RMarkdown by default (https://www.rdocumentation.org/packages/rmarkdown/versions/1.10/topics/rmarkdown_format) so it would seem to make sense to enable that at least for the markdown+r mode.

**Comment by vspinu** [comment]
There are 2 pandoc extensions, one for single and one for double backslashed. I am guessing R markdown activates the single backslashed one, or it does both?

**Comment by ahonkela** [comment]
"By default R Markdown is defined as all pandoc markdown extensions with the following tweaks for backward compatibility with the markdown package:

+autolink_bare_uris
+ascii_identifier
+tex_math_single_backslash"
(https://rmarkdown.rstudio.com/html_document_format#markdown_extensions)

**Comment by vspinu** [comment]
Well, "all" need not always mean "all", you know;) 

Could you please try `\\[..\\]` and `\\(..\\)` blocks and see if it does work? I cannot do it myself because it don't even have a good idea of what "does work" mean in this context as I never used math in Rmarkdown. 

This is mostly out of curiosity. I am unlikely to implement the double backslashed versions unless someone really cannot do without at some point in the future.
